// <auto-generated />
using System;
using CarRentalPortfolio.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BFC.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260413152755_AddHomeLabels")]
    partial class AddHomeLabels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("CarRentalPortfolio.Models.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Admins");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Password = "Bakora@car",
                            Username = "Bakora"
                        });
                });

            modelBuilder.Entity("CarRentalPortfolio.Models.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DescriptionAr")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FuelType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FuelTypeAr")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PricePerDay")
                        .HasColumnType("TEXT");

                    b.Property<int>("Seats")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Transmission")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TransmissionAr")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Luxury sedan with executive comfort. Features premium leather interior, advanced driver assistance systems, and a powerful hybrid engine for a smooth, quiet ride.",
                            DescriptionAr = "سيارة سيدان فاخرة مع راحة تنفيذية. تتميز بمقصورة داخلية من الجلد الفاخر، وأنظمة مساعدة متقدمة للسائق، ومحرك هايبرد قوي لقيادة سلسة وهادئة.",
                            FuelType = "Hybrid",
                            FuelTypeAr = "هايبرد",
                            ImageUrl = "/images/mercedes-s-class.jpg",
                            IsAvailable = true,
                            Name = "Mercedes-Benz S-Class",
                            NameAr = "مرسيدس بنز إس كلاس",
                            PricePerDay = 3500m,
                            Seats = 5,
                            Transmission = "Automatic",
                            TransmissionAr = "أوتوماتيك",
                            Year = 2024
                        },
                        new
                        {
                            Id = 2,
                            Description = "Ultimate driving machine with premium features. Combines luxury with sporty performance, featuring cutting-edge technology and unparalleled comfort.",
                            DescriptionAr = "سيارة القيادة المثالية مع ميزات فاخرة. تجمع بين الفخامة والأداء الرياضي، وتتميز بأحدث التقنيات وراحة لا مثيل لها.",
                            FuelType = "Petrol",
                            FuelTypeAr = "بنزين",
                            ImageUrl = "/images/bmw-7.jpg",
                            IsAvailable = true,
                            Name = "BMW 7 Series",
                            NameAr = "بي إم دبليو الفئة السابعة",
                            PricePerDay = 3200m,
                            Seats = 5,
                            Transmission = "Automatic",
                            TransmissionAr = "أوتوماتيك",
                            Year = 2024
                        },
                        new
                        {
                            Id = 3,
                            Description = "Luxury SUV with off-road capabilities. Perfect for both city driving and adventurous terrain, offering supreme comfort and powerful performance.",
                            DescriptionAr = "سيارة دفع رباعي فاخرة مع قدرات للطرق الوعرة. مثالية للقيادة في المدينة والمغامرات على حد سواء، وتوفر راحة فائقة وأداء قوي.",
                            FuelType = "Diesel",
                            FuelTypeAr = "ديزل",
                            ImageUrl = "/images/range-rover.jpg",
                            IsAvailable = true,
                            Name = "Range Rover Sport",
                            NameAr = "رينج روفر سبورت",
                            PricePerDay = 4000m,
                            Seats = 7,
                            Transmission = "Automatic",
                            TransmissionAr = "أوتوماتيك",
                            Year = 2024
                        },
                        new
                        {
                            Id = 4,
                            Description = "Iconic sports car with exhilarating performance. Experience the thrill of driving with precision handling and breathtaking speed.",
                            DescriptionAr = "سيارة رياضية أيقونية بأداء مثير. اختبر متعة القيادة مع تحكم دقيق وسرعة مذهلة.",
                            FuelType = "Petrol",
                            FuelTypeAr = "بنزين",
                            ImageUrl = "/images/porsche-911.jpg",
                            IsAvailable = true,
                            Name = "Porsche 911",
                            NameAr = "بورش 911",
                            PricePerDay = 4500m,
                            Seats = 4,
                            Transmission = "Automatic",
                            TransmissionAr = "أوتوماتيك",
                            Year = 2024
                        },
                        new
                        {
                            Id = 5,
                            Description = "Ultra-luxury SUV with Japanese craftsmanship. Combines off-road capability with exquisite interior detailing and reliable performance.",
                            DescriptionAr = "سيارة دفع رباعي فاخرة مع حرفية يابانية. تجمع بين قدرات الطرق الوعرة والتفاصيل الداخلية الفاخرة والأداء الموثوق.",
                            FuelType = "Petrol",
                            FuelTypeAr = "بنزين",
                            ImageUrl = "/images/lexus-lx.jpg",
                            IsAvailable = true,
                            Name = "Lexus LX",
                            NameAr = "لكزس LX",
                            PricePerDay = 3800m,
                            Seats = 7,
                            Transmission = "Automatic",
                            TransmissionAr = "أوتوماتيك",
                            Year = 2024
                        },
                        new
                        {
                            Id = 6,
                            Description = "Sophisticated luxury sedan with cutting-edge technology. Features a quiet cabin, advanced suspension, and intuitive controls for a refined driving experience.",
                            DescriptionAr = "سيارة سيدان فاخرة متطورة بأحدث التقنيات. تتميز بمقصورة هادئة، ونظام تعليق متقدم، وأدوات تحكم بديهية لتجربة قيادة راقية.",
                            FuelType = "Hybrid",
                            FuelTypeAr = "هايبرد",
                            ImageUrl = "/images/audi-a8.jpg",
                            IsAvailable = true,
                            Name = "Audi A8",
                            NameAr = "أودي A8",
                            PricePerDay = 3300m,
                            Seats = 5,
                            Transmission = "Automatic",
                            TransmissionAr = "أوتوماتيك",
                            Year = 2024
                        });
                });

            modelBuilder.Entity("CarRentalPortfolio.Models.ContactMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRead")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ContactMessages");
                });

            modelBuilder.Entity("CarRentalPortfolio.Models.HeroImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Subtitle")
                        .HasColumnType("TEXT");

                    b.Property<string>("SubtitleAr")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<string>("TitleAr")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("HeroImages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "/images/hero-bg.jpg",
                            IsActive = true,
                            Subtitle = "Discover our curated collection of premium vehicles",
                            SubtitleAr = "اكتشف مجموعتنا المختارة من السيارات الراقية",
                            Title = "Luxury Cars, Exceptional Experience",
                            TitleAr = "سيارات فاخرة بتجربة استثنائية"
                        });
                });

            modelBuilder.Entity("CarRentalPortfolio.Models.SiteSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccentColor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AccentDarkColor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BackgroundColor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CarsSubtitleAr")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CarsSubtitleEn")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CarsTitleAr")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CarsTitleEn")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactSubtitleAr")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactSubtitleEn")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactTitleAr")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactTitleEn")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FaviconUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("FeaturesTitleAr")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FeaturesTitleEn")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FooterTextAr")
                        .HasColumnType("TEXT");

                    b.Property<string>("FooterTextEn")
                        .HasColumnType("TEXT");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhilosophyAr")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhilosophyEn")
                        .HasColumnType("TEXT");

                    b.Property<string>("PrimaryColor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PrimaryDarkColor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PrimaryLightColor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SiteName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SiteNameAr")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SurfaceColor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TestimonialsTitleAr")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TestimonialsTitleEn")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TextDarkColor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TextLightColor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("WhatsAppMessageAr")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WhatsAppMessageEn")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WhatsAppNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SiteSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccentColor = "#f6bd2c",
                            AccentDarkColor = "#e5a913",
                            BackgroundColor = "#d0d7d1",
                            CarsSubtitleAr = "اختر سيارتك المثالية واستمتع بتجربة قيادة لا تُنسى",
                            CarsSubtitleEn = "Choose your perfect car and enjoy an unforgettable driving experience",
                            CarsTitleAr = "سياراتنا الفاخرة",
                            CarsTitleEn = "Our Luxury Fleet",
                            ContactSubtitleAr = "نحن هنا لمساعدتك 24 ساعة طوال أيام الأسبوع عبر واتساب",
                            ContactSubtitleEn = "We're here to help you 24/7 via WhatsApp",
                            ContactTitleAr = "تواصل معنا",
                            ContactTitleEn = "Contact Us",
                            FaviconUrl = "/images/icon.png",
                            FeaturesTitleAr = "مميزاتنا",
                            FeaturesTitleEn = "Our Advantages",
                            FooterTextAr = "تأجير سيارات فاخرة في مصر",
                            FooterTextEn = "Luxury Car Rental in Egypt",
                            LogoUrl = "/images/icon.png",
                            PhilosophyAr = "راحتك هي أولويتنا القصوى",
                            PhilosophyEn = "Your comfort is our top priority",
                            PrimaryColor = "#6f9883",
                            PrimaryDarkColor = "#5a7a69",
                            PrimaryLightColor = "#8fb19e",
                            SiteName = "H-CAR",
                            SiteNameAr = "إتش-كار",
                            SurfaceColor = "#ffffff",
                            TestimonialsTitleAr = "ماذا يقول عملاؤنا",
                            TestimonialsTitleEn = "What Our Clients Say",
                            TextDarkColor = "#1e2b27",
                            TextLightColor = "#5a6b64",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WhatsAppMessageAr = "مرحباً، أود الاستفسار عن تأجير سيارة",
                            WhatsAppMessageEn = "Hello, I'm interested in renting a car",
                            WhatsAppNumber = "201065646972"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
